wiki_corpus:
    wiki_path: /path/to/wikisep.txt
flickr_dataset:
    annotation_dir_path: /path/to/annotations/
    tag_dir_path: /path/to/mirflickr/
word2vec_model:
    model_path: /path/to/enwiki_word2vec_200dim.dat
features:
    image_feature_path: /path/to/img_features.npy
    word_feature_path: /path/to/word_features.npy
cca_data:
    cca_dir_path:  /path/to/cca_data/